// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjvbxjpiebtvdmxyeuhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqdmJ4anBpZWJ0dmRteHlldWhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTY0ODEsImV4cCI6MjA2ODA3MjQ4MX0.uwSvuNgilj8RUwWC0HFvYXtt1v-9_2vbNYFDX2TqmEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});